<a href="https://colab.research.google.com/github/angeruzzi/FundamentosPython/blob/main/Biblioteca_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A Biblioteca numpy é utilizada para manipulação e cálculos em Arrays


In [1]:
import numpy as np

In [2]:
#Declaração de um ndarray, o objeto de tipo array utilizado pela biblioteca
np.array([1,2,3,4])


array([1, 2, 3, 4])

In [41]:
type(np.array([1,2,3,4]))

numpy.ndarray

In [4]:
#Multiplicação em uma lista simples
3*[1,2,3,4]

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [5]:
#Multiplicação em um ndarray
3*np.array([1,2,3,4])

array([ 3,  6,  9, 12])

In [17]:
#Bidimensional
n2 = np.array([[1,2,3,4],[3,2,4,6]])

#Dimensões do array
n2.shape

(2, 4)

In [24]:
#Preenchimento do array com preenchimento Automático
n3 = np.arange(10,33,2)
n3

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

In [25]:
#Reorganização do array
n3.reshape((3,4))

array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [32]:
#Geração randômica de arrays
np.random.random((5,2))

array([[0.5275964 , 0.85256688],
       [0.75165654, 0.67931598],
       [0.98139294, 0.66834041],
       [0.88805603, 0.18546733],
       [0.54089079, 0.31291425]])

In [26]:
np.random.choice([1, 2, 3, 4, 5], size = 3)

array([5, 5, 1])

In [34]:
#Teste de Valores
np.all([True,True,True,True,True])

True

In [35]:
np.any([True,False,False,False,False])

True

In [39]:
#Operações entre arrays

a = np.array([[1.0, 2.0], [3.0, 4.0]])
b = np.array([[5.0, 6.0], [7.0, 8.0]])

#Por Elemento
print('Soma = \n', a + b)
print('\n')
print('Diferença = \n', a - b)
print('\n')
print('Multiplicação  = \n', a * b)
print('\n')
print('Divisão = \n', a / b)

Soma = 
 [[ 6.  8.]
 [10. 12.]]


Diferença = 
 [[-4. -4.]
 [-4. -4.]]


Multiplicação  = 
 [[ 5. 12.]
 [21. 32.]]


Divisão = 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [40]:
print('Multiplicação de Matriz = \n', a.dot(b))

Multiplicação de Matriz = 
 [[19. 22.]
 [43. 50.]]
